### ISSUE TITLE
Edit metadata values: “add to all” control in imeji is splitted -> confusing

### ISSUE THREAD

**Issue by kristinaMPDL** [MPDL/imeji_sass#20]
![grafik](https://user-images.githubusercontent.com/14921701/31232382-0491d814-a9ea-11e7-8666-a93dc5e754dc.png)

 
![grafik](https://user-images.githubusercontent.com/14921701/31232369-fe71d038-a9e9-11e7-8f90-56114419cb01.png)

**Comment by bastiensaquet** [comment]
done
