### ISSUE TITLE
Collected issues testing Outbox CSS in imeji v4.1

### ISSUE THREAD

**Issue by ioverka** [MPDL/imeji_sass#21]
Testserver: qa-edmond
Browser: ff
Version: version 4.0.1.1-SNAPSHOT - build date 2017-10-10 16:47:40 
User: standard user

1. START PAGE - the dreaded upload link is back :) - DONE

2. EDIT ITEM - OPEN
There seems to be a blank ahead of the input element for the file name:
![imeji-blank](https://user-images.githubusercontent.com/8920469/31745308-7b8b2dd0-b462-11e7-8614-309b5a12693a.png)

3. SHARE COLLECTION - MOVED to MPDL/imeji#921
Is "update list" really a good label for the action? Wouldn't "save changes" be more appropriate?
![imeji-update-list](https://user-images.githubusercontent.com/8920469/31745742-61e0f1e2-b464-11e7-8341-128aed5b33b6.png)

**Comment by bastiensaquet** [comment]
Done
