### ISSUE TITLE
Facet count may wrap to new line

### ISSUE THREAD

**Issue by ioverka** [MPDL/imeji_sass#24]
Server: outbox
Browser: ff
Version: 4.1.0 - build date 2017-10-11 16:37:33 

If the item list is zoomed to 150%, the facet count of date elements wraps to a new line:
![date-wrap](https://user-images.githubusercontent.com/8920469/32402364-4cf12ade-c122-11e7-8b40-51913ae54f7b.png)

Question: Can this been avoided?

If not, could we at least reduce the top margin?

**Comment by bastiensaquet** [comment]
Done.
