### ISSUE TITLE
Edmond GUI: Different fond sizes and types

### ISSUE THREAD

**Issue by kristinaMPDL** [MPDL/imeji_sass#8]
@kristinaMPDL commented on [Wed Jun 28 2017](https://github.com/MPDL/imeji/issues/810)

1. Release Collection:
![grafik](https://user-images.githubusercontent.com/5978196/27632729-f4a5810c-5bfc-11e7-826e-36c83a4c8cf9.png)

2. Edit All:
![grafik](https://user-images.githubusercontent.com/5978196/27632760-06410d78-5bfd-11e7-8b49-9a0f2cfb8952.png)

3. Menu:
![grafik](https://user-images.githubusercontent.com/5978196/27632793-1c8da622-5bfd-11e7-882b-83daadc08f07.png)

**Comment by bastiensaquet** [comment]
1: done
2 & 3: was intended so. We can discuss about it if you think this should be changed

**Comment by kristinaMPDL** [comment]
As discussed with Bastien:
2: is fine with me and can stay as it is
3: The fond size from UPLOAD and New collection is different. Bastien will try it with two similar fond sizes.
