### ISSUE TITLE
Edmond GUI: Edit selected Items: Sämtliches Edmond Layout ist verschwunden, der Hintergrund ist komplett weiß

### ISSUE THREAD

**Issue by kristinaMPDL** [MPDL/imeji_sass#9]
@kristinaMPDL commented on [Wed Jun 28 2017](https://github.com/MPDL/imeji/issues/809)

![grafik](https://user-images.githubusercontent.com/5978196/27632693-c926b316-5bfc-11e7-8359-78b1d636c5e8.png)

**Comment by bastiensaquet** [comment]
This is intended so. What would you expect?

**Comment by kristinaMPDL** [comment]
Bastien wants to use the whole display for this functionality. My proposal would be to stay in the content filed within Edmond.
As discussed with Bastien I will ask Inga and Lu for their opinion.

**Comment by ioverka** [comment]
I actually was fine with the "full screen display" for this particular interface. 

On the other hand side, I predict that the Outbox will only have a limited set of metadata statements - so the width of the content area is probably sufficient for my scenario.

Thus: I'll leave the decision to @kristinaMPDL and @cafefish :)

**Comment by kristinaMPDL** [comment]
As for Edmond, the background color is now displayed
